CREATE TABLE product (
"PRODUCTID" text PRIMARY KEY,
"PRODUCTNDC" text,
"PRODUCTTYPENAME" text,
"PROPRIETARYNAME" text,
"PROPRIETARYNAMESUFFIX" text,
"NONPROPRIETARYNAME" text,
"DOSAGEFORMNAME" text,
"ROUTENAME" text,
"STARTMARKETINGDATE" text,
"ENDMARKETINGDATE" text,
"MARKETINGCATEGORYNAME" text,
"APPLICATIONNUMBER" text,
"LABELERNAME" text,
"SUBSTANCENAME" text,
"ACTIVE_NUMERATOR_STRENGTH" text,
"ACTIVE_INGRED_UNIT" text,
"PHARM_CLASSES" text,
"DEASCHEDULE" text,
"NDC_EXCLUDE_FLAG" text,
"LISTING_RECORD_CERTIFIED_THROUGH" text
);

CREATE TABLE package (
"PRODUCTID" text PRIMARY KEY,
"PRODUCTNDC" text,
"NDCPACKAGECODE" text,
"PACKAGEDESCRIPTION" text,
"STARTMARKETINGDATE" text,
"ENDMARKETINGDATE" text,
"NDC_EXCLUDE_FLAG" text,
"SAMPLE_PACKAGE" text
);